kind: pipeline
type: docker
name: default

steps:
  - name: check-code-style
    image: python:3.11
    commands:
      - pip install black
      - black --check agent/ client/ server/ components/

  - name: lint-and-security-check
    image: python:3.11
    commands:
      - pip install flake8 bandit
      - flake8 agent/ client/ server/ --exclude='**/venv/**'
      - bandit -r agent/ client/ server/ -x '**/venv/**'

  - name: make-and-check-components
    image: python:3.11
    commands:
      - cd components
      - source venv/bin/activate
      - pip install -r ./requirements.txt
      - make
      - git status --porcelain | grep '^??' && echo "New untracked files detected!" && exit 1 || echo "No new untracked files."
      - git status --porcelain | grep '^\s*D' && echo "Tracked files deleted!" && exit 1 || echo "No tracked files deleted."
    when:
      event:
        - pull_request
trigger:
  event:
    - push
    - pull_request
