version: "3.8"
services:
  agent:
    build: .
    command: python main.py
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
      DATABASE_URL: ${DATABASE_URL}
      TIMEZONE: ${TIMEZONE}
      LOGGER_LEVEL: ${LOGGER_LEVEL}
    networks:
      - multicat
networks:
  multicat:
    external: true
